### ISSUE TITLE
Сделать цветовую гамму для темной/светлой темы на макете в figma

### ISSUE THREAD

**Issue by 6ocra3** [6ocra3/y-frontend-project#23]

**Comment by sherstnew** [comment]
https://www.figma.com/file/ap6r3v6qVvkXPjtGguMU2l/Сайт-визитка-команды?node-id=157%3A481&t=jUlYU1WPBSppRyEE-0
смотрим, оцениваем, пишем

**Comment by JeeEssEm** [comment]
![Screenshot_20221215-231402_Chrome](https://user-images.githubusercontent.com/67123971/207957845-0d36b37c-8774-47de-a1ba-d9a4024bb390.jpg)

Какая-то суета под Андреем Никитиным, а всё остальное збс.
UPD: что-то со значком местоположения: внутренний круг сливается с фоном

**Comment by sherstnew** [comment]
Белым выделяется тот адрес, который выбран на карте, значок местоположения пофиксил
